#bash scripts/run_test_zeroshot.sh configs/hmdb51/hmdb_test.yaml exps_MoTE/hmdb51/ViT-B/16/20250919_094629/model_best.pt --test_clips 1
#bash scripts/run_test_zeroshot.sh configs/hmdb51/hmdb_test.yaml exps_MoTE/hmdb51/ViT-B/16/20250919_083454/model_best.pt --test_clips 1

seed: 1024
data:
    dataset: hmdb51
    modality: video
    num_segments: 8
    seg_length: 1
    batch_size: 256
    workers: 8
    num_classes: 51
    image_tmpl: 'image_{:06d}.jpg'
    val_root: 'xxxx/hmdb51'
    val_list: 'lists/hmdb51/test.txt'    
    val_desc_list: 'lists/hmdb51/test_desc.csv'
    label_list: 'lists/hmdb51/hmdb51_rephrase_merged.csv'
    spatial_label_list: 'lists/hmdb51/hmdb51_spatial_label.csv'
    template_label_list: 'lists/hmdb51/hmdb51_temporal_label.csv'
    index_bias: 1
    input_size: 224
network:
    arch: ViT-B/16 # ViT-L/14 
    init: True
    drop_out: 0.0
    emb_dropout: 0.0
    sim_header: Transf # Transf, None
    interaction: DP    # DP
    num_experts: 4  #  >1: MoTE; <=1: mlp
logging:
    print_freq: 10
    eval_freq: 1